/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gwve.test;

import java.io.File;
import java.io.IOException;
import java.lang.reflect.InvocationTargetException;

import com.gemiso.gwve.ffmpeg.commands.GwveFfmpegCommand;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException, NoSuchMethodException, SecurityException {
        String normal_path = "C:\\PROJECT\\Server\\gve-java\\gwve-gradle\\app\\asset\\command.json";   
        String fade_path = "C:\\PROJECT\\Server\\gve-java\\gwve-gradle\\app\\asset\\command_fade.json";   
        String text_test_json_path = "C:\\PROJECT\\Server\\gve-java\\gwve-gradle\\app\\asset\\command_text.json"; 
        String text_test_json_path2 = "C:\\PROJECT\\Server\\gve-java\\gwve-gradle\\app\\asset\\commnad_text2.json";     
        String fontListpath = "C:\\PROJECT\\Server\\gve-java\\gwve-gradle\\app\\asset\\fontList.json";     
        String fontTempPath = "C:\\PROJECT\\Server\\gve-java\\gwve-gradle\\app\\tmp";  
        String exportPath = "C:\\exports";
        String exportFile = "test.mp4";

        try {
            File jsonFile = new File(text_test_json_path2);
            GwveFfmpegCommand gwveFfmpegCommand = new GwveFfmpegCommand(jsonFile);    
            System.out.println(new App().getGreeting());
            gwveFfmpegCommand.setUseFontListJsonFilePath(fontListpath);
            gwveFfmpegCommand.setTempFontTextPath(fontTempPath);
            gwveFfmpegCommand.setExportPath(exportPath);
            gwveFfmpegCommand.setExportFile(exportFile);
            gwveFfmpegCommand.initFontList();
            gwveFfmpegCommand.initFfmpegCommand();
            String ffmpegCommand = gwveFfmpegCommand.generateCommand().getCommand();
            System.out.println("ffmpegCommand >>>>");
            System.out.println(ffmpegCommand);
            System.out.println(" ################# ");

        } catch (IOException e) {

        }
        
    }
}
